"""Google Calendar synchronization for generated study schedules."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

from core.optimizer import StudyBlock

logger = logging.getLogger(__name__)

try:
    from google.auth.transport.requests import Request  # type: ignore[reportMissingImports]
    from google.oauth2.credentials import Credentials  # type: ignore[reportMissingImports]
    from google_auth_oauthlib.flow import InstalledAppFlow  # type: ignore[reportMissingImports]
    from googleapiclient.discovery import build  # type: ignore[reportMissingImports]
except ImportError:  # pragma: no cover
    Request = None
    Credentials = None
    InstalledAppFlow = None
    build = None


SCOPES = ["https://www.googleapis.com/auth/calendar"]


@dataclass(frozen=True)
class CalendarSyncConfig:
    """File paths and defaults for Google Calendar synchronization."""

    credentials_path: str = "credentials.json"
    token_path: str = "token.json"
    calendar_id: str = "primary"
    timezone: str = "UTC"
    reminder_minutes_before: int = 10
    review_color_id: str = "5"  # Yellow
    study_color_id: str = "2"  # Green


class CalendarSyncError(RuntimeError):
    """Raised when calendar authentication or synchronization fails."""


def _ensure_google_deps() -> None:
    if not all([Request, Credentials, InstalledAppFlow, build]):
        raise CalendarSyncError(
            "Google Calendar dependencies missing. Install requirements and retry."
        )


def build_calendar_service(config: CalendarSyncConfig):
    """
    Build an authenticated Google Calendar API service.

    Stores OAuth tokens in `token_path` and refreshes when possible.
    """
    _ensure_google_deps()
    credentials_file = Path(config.credentials_path)
    token_file = Path(config.token_path)
    creds = None

    if token_file.exists():
        creds = Credentials.from_authorized_user_file(str(token_file), SCOPES)

    if creds and creds.valid:
        return build("calendar", "v3", credentials=creds)

    if creds and creds.expired and creds.refresh_token:
        try:
            creds.refresh(Request())
        except Exception as exc:  # noqa: BLE001
            logger.warning("Token refresh failed; re-running OAuth flow: %s", exc)
            creds = None

    if creds is None:
        if not credentials_file.exists():
            raise CalendarSyncError(
                f"Google OAuth client file not found: {credentials_file.resolve()}"
            )
        flow = InstalledAppFlow.from_client_secrets_file(str(credentials_file), SCOPES)
        creds = flow.run_local_server(port=0)

    token_file.write_text(creds.to_json(), encoding="utf-8")
    return build("calendar", "v3", credentials=creds)


def sync_study_blocks_to_calendar(
    blocks: list[StudyBlock],
    *,
    config: Optional[CalendarSyncConfig] = None,
    calendar_service=None,
    event_prefix: str = "Study Plan",
) -> list[str]:
    """
    Sync study/review blocks to Google Calendar.

    Returns:
        List of created Google Calendar event IDs.
    """
    if not blocks:
        return []
    cfg = config or CalendarSyncConfig()
    service = calendar_service or build_calendar_service(cfg)

    created_ids: list[str] = []
    for block in blocks:
        start_dt = datetime.combine(block.date, block.start_time)
        end_dt = start_dt + timedelta(minutes=block.duration_minutes)
        color_id = cfg.review_color_id if block.type == "review" else cfg.study_color_id

        payload = {
            "summary": f"{event_prefix}: {block.topic}",
            "description": (
                f"Auto-generated by Personalization Engine.\n"
                f"Type: {block.type}\n"
                f"Duration: {block.duration_minutes} minutes"
            ),
            "start": {"dateTime": start_dt.isoformat(), "timeZone": cfg.timezone},
            "end": {"dateTime": end_dt.isoformat(), "timeZone": cfg.timezone},
            "colorId": color_id,
            "reminders": {
                "useDefault": False,
                "overrides": [{"method": "popup", "minutes": cfg.reminder_minutes_before}],
            },
        }
        try:
            result = (
                service.events()
                .insert(calendarId=cfg.calendar_id, body=payload, sendUpdates="none")
                .execute()
            )
            created_ids.append(result["id"])
        except Exception as exc:  # noqa: BLE001
            logger.exception("Failed creating calendar event for block %s: %s", block, exc)
            raise CalendarSyncError(f"Failed to sync schedule: {exc}") from exc

    return created_ids
